### ISSUE TITLE
[Android] compileSdkVersion=33 prevents build

### ISSUE THREAD

**Issue by oliviermtl** [mateusz1913/react-native-avoid-softinput#90]
### Environment

Library version: 2.4.6
OS version: Android 12

### Affected platforms

- [X] Android
- [ ] iOS

### Current behavior

Does not build on android
Error messages :

> Task :react-native-avoid-softinput:compileDebugKotlin FAILED

 node_modules/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputManager.kt: (310, 11): 'onAnimationEnd' overrides nothing

Type mismatch: inferred type is Animator? but Animator was expected

### Expected behavior

should build on android with compileSdkVersion=33

### Reproduction

https://github.com/oliviermtl/avoid-softinput

**Comment by mateusz1913** [comment]
Hi @oliviermtl, this issue is fixed from v2.4.7 🚀

**Comment by arnabJ** [comment]
This issue still crops up on React Native 0.70.2 and Plugin version 3.0.1 with compileSdkVersion=33.

I am getting the error while trying to build a release bundle.

`> Task :react-native-avoid-softinput:compileReleaseKotlin FAILED
e: /Users/inocentum/Developer/ReactNativeProjects/event_gravity_hybrid_app/node_modules/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/animations/AnimationHandlerImpl.kt: (86, 11): 'onAnimationEnd' overrides nothing
e: /Users/inocentum/Developer/ReactNativeProjects/event_gravity_hybrid_app/node_modules/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/animations/AnimationHandlerImpl.kt: (87, 34): Type mismatch: inferred type is Animator? but Animator was expected

FAILURE: Build completed with 2 failures.`

**Comment by mateusz1913** [comment]
Hi @arnabJ , would you be able to make a PR with the fix for v3?

**Comment by arnabJ** [comment]
> 

I have made a PR with the fix: #117

**Comment by arnabJ** [comment]
> Hi @arnabJ , would you be able to make a PR with the fix for v3?

Hi, @mateusz1913 I have made a PR with the fix.

**Comment by mateusz1913** [comment]
Thanks @arnabJ for your contribution! The fix is available in v3.0.2 🎉

**Comment by mateusz1913** [comment]
@hadnet check out how to modify kotlin version - https://mateusz1913.github.io/react-native-avoid-softinput/docs/guides#troubleshooting
